GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/?search_q=Buy

###

GET http://localhost:3000/todos/?category=WORK&status=DONE

###

GET http://localhost:3000/todos/?category=HOME

###

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###