GET http://localhost:3000/todos/?status=TO%20DO

###

GET http://localhost:3000/todos/?priority=HIGH

###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###

GET http://localhost:3000/todos/?search_q=Buy

###

GET http://localhost:3000/todos/?category=WORK&status=DONE

###

GET http://localhost:3000/todos/?category=HOME

###

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###

GET http://localhost:3000/todos/5/

###

GET http://localhost:3000/agenda/?date=2021-02-22

###

POST http://localhost:3000/todos/ 
Content-Type: application/json

{
  "id": 9,
  "todo": "Learn Algebra",
  "priority": "MEDIUM",
  "status": "TO DO",
  "category": "LEARNING",
  "dueDate": "2022-09-22"
}

###

PUT http://localhost:3000/todos/5/
Content-Type: application/json

{
  "dueDate": "2020-11"
}

###

DELETE http://localhost:3000/todos/7/ 

###
